//@flow 

 // Action Types 
export const CREATE_SOME_NEW_FANCY_SOMETHING_REQUEST: 'CREATE_SOME_NEW_FANCY_SOMETHING_REQUEST' = 'CREATE_SOME_NEW_FANCY_SOMETHING_REQUEST';
export const CREATE_SOME_NEW_FANCY_SOMETHING_SUCCESS: 'CREATE_SOME_NEW_FANCY_SOMETHING_SUCCESS' = 'CREATE_SOME_NEW_FANCY_SOMETHING_SUCCESS';
export const CREATE_SOME_NEW_FANCY_SOMETHING_FAILURE: 'CREATE_SOME_NEW_FANCY_SOMETHING_FAILURE' = 'CREATE_SOME_NEW_FANCY_SOMETHING_FAILURE';
export type CREATE_SOME_NEW_FANCY_SOMETHING_REQUEST_ACTION = { type: typeof CREATE_SOME_NEW_FANCY_SOMETHING_REQUEST };
export type CREATE_SOME_NEW_FANCY_SOMETHING_SUCCESS_ACTION = { type: typeof CREATE_SOME_NEW_FANCY_SOMETHING_SUCCESS };
export type CREATE_SOME_NEW_FANCY_SOMETHING_FAILURE_ACTION = { type: typeof CREATE_SOME_NEW_FANCY_SOMETHING_SUCCESS, error: Object };

export const REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_REQUEST: 'REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_REQUEST' = 'REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_REQUEST';
export const REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_SUCCESS: 'REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_SUCCESS' = 'REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_SUCCESS';
export const REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_FAILURE: 'REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_FAILURE' = 'REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_FAILURE';
export type REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_REQUEST_ACTION = { type: typeof REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_REQUEST };
export type REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_SUCCESS_ACTION = { type: typeof REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_SUCCESS };
export type REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_FAILURE_ACTION = { type: typeof REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_SUCCESS, error: Object };

 // Global Action Type 
 export type MY_TYPES = 
| CREATE_SOME_NEW_FANCY_SOMETHING_REQUEST_ACTION
| CREATE_SOME_NEW_FANCY_SOMETHING_SUCCESS_ACTION
| CREATE_SOME_NEW_FANCY_SOMETHING_FAILURE_ACTION

| REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_REQUEST_ACTION
| REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_SUCCESS_ACTION
| REQUEST_NEW_BACKUPS_FOR_PRIVATE_RYAN_FAILURE_ACTION

